# Generated by Django 4.0.3 on 2022-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.IntegerField(default=5)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(default=5)),
                ('dest_name', models.CharField(max_length=25)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('day1', models.CharField(max_length=200)),
                ('day2', models.CharField(max_length=200)),
                ('day3', models.CharField(max_length=200)),
                ('day4', models.CharField(max_length=200)),
                ('day5', models.CharField(max_length=200)),
                ('day6', models.CharField(max_length=200)),
            ],
        ),
    ]
