# Generated by Django 4.0.3 on 2022-04-27 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_alter_passaeger_detail_trip_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('Card_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Ex_month', models.CharField(max_length=2)),
                ('Ex_year', models.CharField(max_length=2)),
                ('CVV', models.CharField(max_length=3)),
                ('Balance', models.CharField(max_length=8)),
                ('email', models.EmailField(default='faizdummimail21@gmail.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NetBanking',
            fields=[
                ('Username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=14)),
                ('Bank', models.CharField(max_length=25)),
                ('Balance', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transactions_ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('Trip_same_id', models.IntegerField(default=1)),
                ('Amount', models.CharField(max_length=8)),
                ('Status', models.CharField(default='Failed', max_length=15)),
                ('Payment_method', models.CharField(blank=True, max_length=15)),
                ('Date_Time', models.CharField(default=datetime.datetime(2022, 4, 27, 8, 18, 5, 306055, tzinfo=utc), max_length=19)),
            ],
        ),
    ]
