# Generated by Django 4.0.3 on 2022-04-29 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_cards_netbanking_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='Balance',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='email',
            field=models.EmailField(default='faizdummimail21@gmail.com', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 4, 29, 20, 29, 0, 967325, tzinfo=utc), max_length=19),
        ),
    ]
