# Generated by Django 4.0.3 on 2022-05-02 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_alter_cards_balance_alter_cards_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 5, 2, 10, 23, 3, 294380, tzinfo=utc), max_length=100),
        ),
    ]
