# Generated by Django 4.0.3 on 2022-05-04 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='day6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 5, 4, 10, 59, 34, 403338, tzinfo=utc), max_length=100),
        ),
    ]
