# Generated by Django 4.0.3 on 2022-05-04 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_alter_detailed_desc_day6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='day6',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 5, 4, 11, 3, 0, 527514, tzinfo=utc), max_length=100),
        ),
    ]
